# Generated by Django 3.2.12 on 2024-04-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loan_application_accepted', models.BooleanField(default=False)),
                ('is_document_submitted', models.BooleanField(default=False)),
                ('is_screening_done', models.BooleanField(default=False)),
                ('is_negotiation_done', models.BooleanField(default=False)),
                ('is_loan_finalized', models.BooleanField(default=False)),
                ('is_loan_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IterationModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
